In [ ]:
import requests
import json
import time
import hashlib
import hmac
import base64

# API Key
API_KEY = 'eV3wFrpclIBrZYuaCwxXBZ1oJDM2r0Kw'
BASE_URL = 'http://api.asocks.com/v2'

# Generate signature (if required for additional security features)
def generate_signature(secret_key, http_method, url, timestamp, body=''):
    data = f"{timestamp}{http_method.upper()}{url}{body}"
    signature = hmac.new(secret_key.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).digest()
    return base64.b64encode(signature).decode()

# Example API call functions

# Get user balance
def get_user_balance():
    url = f"{BASE_URL}/user/balance?apiKey={API_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# Get tariff information
def get_tariff_info():
    url = f"{BASE_URL}/plan/info?apiKey={API_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# Create a new proxy port
def create_proxy_port():
    url = f"{BASE_URL}/proxy/create-port?apiKey={API_KEY}"
    response = requests.post(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# List all proxy ports
def list_proxy_ports():
    url = f"{BASE_URL}/proxy/ports?apiKey={API_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# Refresh a proxy port's IP
def refresh_proxy_ip(port_id):
    url = f"{BASE_URL}/proxy/refresh/{port_id}?apiKey={API_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code} - {response.text}")
        return None

# Example usage
user_balance = get_user_balance()
tariff_info = get_tariff_info()
proxy_ports = list_proxy_ports()

# Display the results
if user_balance:
    print("User Balance:", user_balance)

if tariff_info:
    print("Tariff Information:", tariff_info)

if proxy_ports:
    print("Proxy Ports:", proxy_ports)

# Function to save the notebook
# import ace_tools as tools; tools.display_ipynb_to_user('Asocks_API_Example')

In [ ]:
!ls

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json

# read json as df 
json_data = open('scraped_data_with_positions.json')
data = json.load(json_data)

In [21]:
df = pd.DataFrame(data)

In [ ]:
# display Bin and Price
df[['Bin', 'Price']]
# raning based on Price
# df.sort_values('Price', ascending=False)
# and display only Bin Price and Expiry

df[['Bin', 'Price', 'Expiry']].sort_values('Price', ascending=True).head(30)

        Bin          Price Expiry
359  526924  10.50 $ 21.00  01/25
260  477874  10.50 $ 21.00  01/25
425  483313  10.50 $ 21.00  01/25
751  440393  10.50 $ 21.00  01/25
342  400022  10.50 $ 21.00  01/25
734  376793        15.75 $  06/28
554  376798        15.75 $  11/27
500  376783        18.90 $  07/28
361  410039        21.00 $  08/26
706  440393        21.00 $  10/28
358  601120        21.00 $  06/25
364  481583        21.00 $  11/28
357  510805        21.00 $  09/25
356  400022        21.00 $  11/27
704  400022        21.00 $  04/27
365  483313        21.00 $  06/28
366  537811        21.00 $  12/26
362  514968        21.00 $  06/28
449  400022        21.00 $  07/26
352  447098        21.00 $  02/25

:

In [30]:
import requests

def get_bin_data(bin_id):
    try:
        response = requests.get(f'https://data.handyapi.com/bin/{bin_id}', headers={'Referer': 'your-domain'})
        if response.status_code == 200:
            data = response.json()
            return {
                'Type': data.get('Type'),
                'Issuer': data.get('Issuer'),
                'CardTier': data.get('CardTier'),
                'CountryName': data.get('Country', {}).get('Name')
            }
        else:
            return {'Type': None, 'Issuer': None, 'CardTier': None, 'CountryName': None}
    except Exception as e:
        return {'Type': None, 'Issuer': None, 'CardTier': None, 'CountryName': None}


get_bin_data(535316)

{'Type': 'CREDIT',
 'Issuer': 'COMMONWEALTH BANK OF AUSTRALIA',
 'CardTier': 'PLATINUM MASTERCARD',
 'CountryName': 'Australia'}

In [31]:
# bin_data = df['Bin'].apply(get_bin_data)

# write this as iterraion to avoid getting blocked

bin_data = []
for bin_id in df['Bin']:
    bin_data.append(get_bin_data(bin_id))
    print(f'Bin {bin_id} data fetched')

Bin 427082 data fetched
Bin 483313 data fetched
Bin 414709 data fetched
Bin 440393 data fetched
Bin 498503 data fetched
Bin 439911 data fetched
Bin 559591 data fetched
Bin 440393 data fetched
Bin 527520 data fetched
Bin 483313 data fetched
Bin 517545 data fetched
Bin 414709 data fetched
Bin 414709 data fetched
Bin 601101 data fetched
Bin 448592 data fetched
Bin 542432 data fetched
Bin 426684 data fetched
Bin 409311 data fetched
Bin 512230 data fetched
Bin 559767 data fetched
Bin 411770 data fetched
Bin 400022 data fetched
Bin 532839 data fetched
Bin 434769 data fetched
Bin 550806 data fetched
Bin 446540 data fetched
Bin 438857 data fetched
Bin 443051 data fetched
Bin 455225 data fetched
Bin 478200 data fetched
Bin 411770 data fetched
Bin 528620 data fetched
Bin 483313 data fetched
Bin 546511 data fetched
Bin 518725 data fetched
Bin 478200 data fetched
Bin 434769 data fetched
Bin 518941 data fetched
Bin 601100 data fetched
Bin 426684 data fetched
Bin 443049 data fetched
Bin 512992 data fetched
Bin 406032 data fetched
Bin 420064 data fetched
Bin 601129 data fetched
Bin 443051 data fetched
Bin 515676 data fetched
Bin 426684 data fetched
Bin 414709 data fetched
Bin 483314 data fetched
Bin 440393 data fetched
Bin 431196 data fetched
Bin 438857 data fetched
Bin 440066 data fetched
Bin 601100 data fetched
Bin 440393 data fetched
Bin 486236 data fetched
Bin 483316 data fetched
Bin 515676 data fetched
Bin 440066 data fetched
Bin 410039 data fetched
Bin 443045 data fetched
Bin 601129 data fetched
Bin 434769 data fetched
Bin 517805 data fetched
Bin 438854 data fetched
Bin 453506 data fetched
Bin 551427 data fetched
Bin 429444 data fetched
Bin 400167 data fetched
Bin 510805 data fetched
Bin 440393 data fetched
Bin 515549 data fetched
Bin 426684 data fetched
Bin 432825 data fetched
Bin 400022 data fetched
Bin 539754 data fetched
Bin 515676 data fetched
Bin 601100 data fetched
Bin 414709 data fetched
Bin 400022 data fetched
Bin 514377 data fetched
Bin 447954 data fetched
Bin 412138 data fetched
Bin 400022 data fetched
Bin 474481 data fetched
Bin 440393 data fetched
Bin 424018 data fetched
Bin 464018 data fetched
Bin 440066 data fetched
Bin 403469 data fetched
Bin 512754 data fetched
Bin 517805 data fetched
Bin 421783 data fetched
Bin 479213 data fetched
Bin 405627 data fetched
Bin 478200 data fetched
Bin 414720 data fetched
Bin 601100 data fetched
Bin 411079 data fetched
Bin 431196 data fetched
Bin 440393 data fetched
Bin 414720 data fetched
Bin 601101 data fetched
Bin 544614 data fetched
Bin 601120 data fetched
Bin 474473 data fetched
Bin 517546 data fetched
Bin 483314 data fetched
Bin 432626 data fetched
Bin 400899 data fetched
Bin 515676 data fetched
Bin 484718 data fetched
Bin 512230 data fetched
Bin 426684 data fetched
Bin 440066 data fetched
Bin 543389 data fetched
Bin 553469 data fetched
Bin 443047 data fetched
Bin 464018 data fetched
Bin 438854 data fetched
Bin 546316 data fetched
Bin 472361 data fetched
Bin 517805 data fetched
Bin 438857 data fetched
Bin 414709 data fetched
Bin 517805 data fetched
Bin 521515 data fetched
Bin 400899 data fetched
Bin 440909 data fetched
Bin 542418 data fetched
Bin 601100 data fetched
Bin 515676 data fetched
Bin 423223 data fetched
Bin 517805 data fetched
Bin 410039 data fetched
Bin 514616 data fetched
Bin 414709 data fetched
Bin 470793 data fetched
Bin 518941 data fetched
Bin 542125 data fetched
Bin 601100 data fetched
Bin 474478 data fetched
Bin 440393 data fetched
Bin 601100 data fetched
Bin 478986 data fetched
Bin 379858 data fetched
Bin 510277 data fetched
Bin 552736 data fetched
Bin 411774 data fetched
Bin 446540 data fetched
Bin 414740 data fetched
Bin 478200 data fetched
Bin 486796 data fetched
Bin 512992 data fetched
Bin 545436 data fetched
Bin 540633 data fetched
Bin 414740 data fetched
Bin 479213 data fetched
Bin 515676 data fetched
Bin 410894 data fetched
Bin 448091 data fetched
Bin 486236 data fetched
Bin 406068 data fetched
Bin 414720 data fetched
Bin 448233 data fetched
Bin 474478 data fetched
Bin 601100 data fetched
Bin 416598 data fetched
Bin 411774 data fetched
Bin 474479 data fetched
Bin 483313 data fetched
Bin 426684 data fetched
Bin 534901 data fetched
Bin 515676 data fetched
Bin 453506 data fetched
Bin 478200 data fetched
Bin 412185 data fetched
Bin 548699 data fetched
Bin 420767 data fetched
Bin 527845 data fetched
Bin 427082 data fetched
Bin 411770 data fetched
Bin 426684 data fetched
Bin 403784 data fetched
Bin 601100 data fetched
Bin 526412 data fetched
Bin 436618 data fetched
Bin 527520 data fetched
Bin 442756 data fetched
Bin 443047 data fetched
Bin 601100 data fetched
Bin 411773 data fetched
Bin 544928 data fetched
Bin 546638 data fetched
Bin 515676 data fetched
Bin 523782 data fetched
Bin 442755 data fetched
Bin 537811 data fetched
Bin 459954 data fetched
Bin 414720 data fetched
Bin 517805 data fetched
Bin 426684 data fetched
Bin 512107 data fetched
Bin 414709 data fetched
Bin 510875 data fetched
Bin 466349 data fetched
Bin 479213 data fetched
Bin 434769 data fetched
Bin 544927 data fetched
Bin 448233 data fetched
Bin 448261 data fetched
Bin 416004 data fetched
Bin 410039 data fetched
Bin 542539 data fetched
Bin 537811 data fetched
Bin 521333 data fetched
Bin 531262 data fetched
Bin 410039 data fetched
Bin 485953 data fetched
Bin 514146 data fetched
Bin 409451 data fetched
Bin 527521 data fetched
Bin 521044 data fetched
Bin 419002 data fetched
Bin 443040 data fetched
Bin 425836 data fetched
Bin 426690 data fetched
Bin 400022 data fetched
Bin 400022 data fetched
Bin 601120 data fetched
Bin 414720 data fetched
Bin 478200 data fetched
Bin 515676 data fetched
Bin 551733 data fetched
Bin 538072 data fetched
Bin 517805 data fetched
Bin 518941 data fetched
Bin 425808 data fetched
Bin 411770 data fetched
Bin 518725 data fetched
Bin 443045 data fetched
Bin 425201 data fetched
Bin 601100 data fetched
Bin 478200 data fetched
Bin 414709 data fetched
Bin 406032 data fetched
Bin 374830 data fetched
Bin 410039 data fetched
Bin 440066 data fetched
Bin 409996 data fetched
Bin 406095 data fetched
Bin 406032 data fetched
Bin 483313 data fetched
Bin 440393 data fetched
Bin 440066 data fetched
Bin 434769 data fetched
Bin 400022 data fetched
Bin 414718 data fetched
Bin 483313 data fetched
Bin 477874 data fetched
Bin 419002 data fetched
Bin 434769 data fetched
Bin 414709 data fetched
Bin 552449 data fetched
Bin 510875 data fetched
Bin 515676 data fetched
Bin 528749 data fetched
Bin 517546 data fetched
Bin 547182 data fetched
Bin 515676 data fetched
Bin 440881 data fetched
Bin 518725 data fetched
Bin 414720 data fetched
Bin 478418 data fetched
Bin 531262 data fetched
Bin 515676 data fetched
Bin 601101 data fetched
Bin 414709 data fetched
Bin 546184 data fetched
Bin 414512 data fetched
Bin 525475 data fetched
Bin 414720 data fetched
Bin 537811 data fetched
Bin 417094 data fetched
Bin 414740 data fetched
Bin 414740 data fetched
Bin 601101 data fetched
Bin 517805 data fetched
Bin 425836 data fetched
Bin 404594 data fetched
Bin 414740 data fetched
Bin 478200 data fetched
Bin 426684 data fetched
Bin 542539 data fetched
Bin 414720 data fetched
Bin 411771 data fetched
Bin 537811 data fetched
Bin 468451 data fetched
Bin 443040 data fetched
Bin 440066 data fetched
Bin 539680 data fetched
Bin 414720 data fetched
Bin 483313 data fetched
Bin 478825 data fetched
Bin 542418 data fetched
Bin 410894 data fetched
Bin 419002 data fetched
Bin 539882 data fetched
Bin 400022 data fetched
Bin 521267 data fetched
Bin 438984 data fetched
Bin 429820 data fetched
Bin 443047 data fetched
Bin 517546 data fetched
Bin 427082 data fetched
Bin 552869 data fetched
Bin 601100 data fetched
Bin 426684 data fetched
Bin 601100 data fetched
Bin 409970 data fetched
Bin 521267 data fetched
Bin 542539 data fetched
Bin 410039 data fetched
Bin 478200 data fetched
Bin 517805 data fetched
Bin 521307 data fetched
Bin 515676 data fetched
Bin 463405 data fetched
Bin 464018 data fetched
Bin 440393 data fetched
Bin 531262 data fetched
Bin 542418 data fetched
Bin 417903 data fetched
Bin 483316 data fetched
Bin 534901 data fetched
Bin 425295 data fetched
Bin 415829 data fetched
Bin 423223 data fetched
Bin 483313 data fetched
Bin 518725 data fetched
Bin 414720 data fetched
Bin 400022 data fetched
Bin 414720 data fetched
Bin 524038 data fetched
Bin 414709 data fetched
Bin 542418 data fetched
Bin 443045 data fetched
Bin 443051 data fetched
Bin 403163 data fetched
Bin 419002 data fetched
Bin 414709 data fetched
Bin 447098 data fetched
Bin 517546 data fetched
Bin 518725 data fetched
Bin 601100 data fetched
Bin 400022 data fetched
Bin 510805 data fetched
Bin 601120 data fetched
Bin 526924 data fetched
Bin 414720 data fetched
Bin 410039 data fetched
Bin 514968 data fetched
Bin 414709 data fetched
Bin 481583 data fetched
Bin 483313 data fetched
Bin 537811 data fetched
Bin 414720 data fetched
Bin 466189 data fetched
Bin 474477 data fetched
Bin 601100 data fetched
Bin 512107 data fetched
Bin 601100 data fetched
Bin 443047 data fetched
Bin 434292 data fetched
Bin 478200 data fetched
Bin 601100 data fetched
Bin 411079 data fetched
Bin 440066 data fetched
Bin 521267 data fetched
Bin 415417 data fetched
Bin 512992 data fetched
Bin 440393 data fetched
Bin 421783 data fetched
Bin 519881 data fetched
Bin 542543 data fetched
Bin 478200 data fetched
Bin 448233 data fetched
Bin 481582 data fetched
Bin 545210 data fetched
Bin 545526 data fetched
Bin 526926 data fetched
Bin 414709 data fetched
Bin 420767 data fetched
Bin 601100 data fetched
Bin 414720 data fetched
Bin 402321 data fetched
Bin 483316 data fetched
Bin 518725 data fetched
Bin 517805 data fetched
Bin 440393 data fetched
Bin 549113 data fetched
Bin 483313 data fetched
Bin 515676 data fetched
Bin 552433 data fetched
Bin 400022 data fetched
Bin 549944 data fetched
Bin 410039 data fetched
Bin 444796 data fetched
Bin 544544 data fetched
Bin 414740 data fetched
Bin 537811 data fetched
Bin 527520 data fetched
Bin 414709 data fetched
Bin 473077 data fetched
Bin 533248 data fetched
Bin 414720 data fetched
Bin 426690 data fetched
Bin 601100 data fetched
Bin 512230 data fetched
Bin 402018 data fetched
Bin 409311 data fetched
Bin 425836 data fetched
Bin 525363 data fetched
Bin 601101 data fetched
Bin 483313 data fetched
Bin 434769 data fetched
Bin 440066 data fetched
Bin 414720 data fetched
Bin 542418 data fetched
Bin 402018 data fetched
Bin 403163 data fetched
Bin 440393 data fetched
Bin 414720 data fetched
Bin 483312 data fetched
Bin 414720 data fetched
Bin 526245 data fetched
Bin 410039 data fetched
Bin 379411 data fetched
Bin 542543 data fetched
Bin 443547 data fetched
Bin 483313 data fetched
Bin 414709 data fetched
Bin 376777 data fetched
Bin 517895 data fetched
Bin 484718 data fetched
Bin 521267 data fetched
Bin 601100 data fetched
Bin 601100 data fetched
Bin 400022 data fetched
Bin 426684 data fetched
Bin 379300 data fetched
Bin 515665 data fetched
Bin 371538 data fetched
Bin 379298 data fetched
Bin 414720 data fetched
Bin 440066 data fetched
Bin 483313 data fetched
Bin 414720 data fetched
Bin 550911 data fetched
Bin 443051 data fetched
Bin 438857 data fetched
Bin 414709 data fetched
Bin 414720 data fetched
Bin 525363 data fetched
Bin 517546 data fetched
Bin 601101 data fetched
Bin 424018 data fetched
Bin 525363 data fetched
Bin 527520 data fetched
Bin 546316 data fetched
Bin 418702 data fetched
Bin 439708 data fetched
Bin 474478 data fetched
Bin 414709 data fetched
Bin 414720 data fetched
Bin 414720 data fetched
Bin 446542 data fetched
Bin 414709 data fetched
Bin 601100 data fetched
Bin 546309 data fetched
Bin 413331 data fetched
Bin 517805 data fetched
Bin 493109 data fetched
Bin 414740 data fetched
Bin 414740 data fetched
Bin 379279 data fetched
Bin 414740 data fetched
Bin 438857 data fetched
Bin 418941 data fetched
Bin 400022 data fetched
Bin 438100 data fetched
Bin 411773 data fetched
Bin 542418 data fetched
Bin 414720 data fetched
Bin 518725 data fetched
Bin 341153 data fetched
Bin 601100 data fetched
Bin 410040 data fetched
Bin 414709 data fetched
Bin 376783 data fetched
Bin 426684 data fetched
Bin 410039 data fetched
Bin 414720 data fetched
Bin 438857 data fetched
Bin 410039 data fetched
Bin 415538 data fetched
Bin 463405 data fetched
Bin 405610 data fetched
Bin 520602 data fetched
Bin 438857 data fetched
Bin 414709 data fetched
Bin 440393 data fetched
Bin 601100 data fetched
Bin 414720 data fetched
Bin 424631 data fetched
Bin 459954 data fetched
Bin 434769 data fetched
Bin 414720 data fetched
Bin 414709 data fetched
Bin 414720 data fetched
Bin 426684 data fetched
Bin 371702 data fetched
Bin 552486 data fetched
Bin 510277 data fetched
Bin 438854 data fetched
Bin 414720 data fetched
Bin 545210 data fetched
Bin 440393 data fetched
Bin 458643 data fetched
Bin 534901 data fetched
Bin 443044 data fetched
Bin 552486 data fetched
Bin 414720 data fetched
Bin 414709 data fetched
Bin 539655 data fetched
Bin 441104 data fetched
Bin 441105 data fetched
Bin 527520 data fetched
Bin 433694 data fetched
Bin 517546 data fetched
Bin 440393 data fetched
Bin 524038 data fetched
Bin 525363 data fetched
Bin 483316 data fetched
Bin 478200 data fetched
Bin 409758 data fetched
Bin 440393 data fetched
Bin 532839 data fetched
Bin 400022 data fetched
Bin 483313 data fetched
Bin 515676 data fetched
Bin 601100 data fetched
Bin 414740 data fetched
Bin 376798 data fetched
Bin 414720 data fetched
Bin 514377 data fetched
Bin 478200 data fetched
Bin 371304 data fetched
Bin 422496 data fetched
Bin 427082 data fetched
Bin 371085 data fetched
Bin 420767 data fetched
Bin 413358 data fetched
Bin 429444 data fetched
Bin 510805 data fetched
Bin 415976 data fetched
Bin 414709 data fetched
Bin 376776 data fetched
Bin 518941 data fetched
Bin 525363 data fetched
Bin 440066 data fetched
Bin 417903 data fetched
Bin 478418 data fetched
Bin 440066 data fetched
Bin 601100 data fetched
Bin 510805 data fetched
Bin 414720 data fetched
Bin 552225 data fetched
Bin 426690 data fetched
Bin 517546 data fetched
Bin 414720 data fetched
Bin 372860 data fetched
Bin 601120 data fetched
Bin 512992 data fetched
Bin 552356 data fetched
Bin 417903 data fetched
Bin 510805 data fetched
Bin 403784 data fetched
Bin 414709 data fetched
Bin 518941 data fetched
Bin 414720 data fetched
Bin 601100 data fetched
Bin 542418 data fetched
Bin 550807 data fetched
Bin 601100 data fetched
Bin 410039 data fetched
Bin 440393 data fetched
Bin 414720 data fetched
Bin 601120 data fetched
Bin 517805 data fetched
Bin 410039 data fetched
Bin 601149 data fetched
Bin 426684 data fetched
Bin 406032 data fetched
Bin 486241 data fetched
Bin 440393 data fetched
Bin 419002 data fetched
Bin 471529 data fetched
Bin 414720 data fetched
Bin 517805 data fetched
Bin 371304 data fetched
Bin 534870 data fetched
Bin 403163 data fetched
Bin 510277 data fetched
Bin 400022 data fetched
Bin 410039 data fetched
Bin 516186 data fetched
Bin 414709 data fetched
Bin 377282 data fetched
Bin 525980 data fetched
Bin 555426 data fetched
Bin 414720 data fetched
Bin 519955 data fetched
Bin 400022 data fetched
Bin 414720 data fetched
Bin 601101 data fetched
Bin 414709 data fetched
Bin 549806 data fetched
Bin 521333 data fetched
Bin 432626 data fetched
Bin 429161 data fetched
Bin 546616 data fetched
Bin 440393 data fetched
Bin 423223 data fetched
Bin 480694 data fetched
Bin 443581 data fetched
Bin 601100 data fetched
Bin 403784 data fetched
Bin 414720 data fetched
Bin 414709 data fetched
Bin 414718 data fetched
Bin 413037 data fetched
Bin 601100 data fetched
Bin 429444 data fetched
Bin 475142 data fetched
Bin 438857 data fetched
Bin 431196 data fetched
Bin 515676 data fetched
Bin 546325 data fetched
Bin 553469 data fetched
Bin 406095 data fetched
Bin 426684 data fetched
Bin 510805 data fetched
Bin 426684 data fetched
Bin 379009 data fetched
Bin 517805 data fetched
Bin 441104 data fetched
Bin 414709 data fetched
Bin 539277 data fetched
Bin 420767 data fetched
Bin 410039 data fetched
Bin 423223 data fetched
Bin 400022 data fetched
Bin 414740 data fetched
Bin 414740 data fetched
Bin 478200 data fetched
Bin 426684 data fetched
Bin 517546 data fetched
Bin 406095 data fetched
Bin 518725 data fetched
Bin 371714 data fetched
Bin 372297 data fetched
Bin 373969 data fetched
Bin 414720 data fetched
Bin 474477 data fetched
Bin 414720 data fetched
Bin 400022 data fetched
Bin 414734 data fetched
Bin 510875 data fetched
Bin 414720 data fetched
Bin 474472 data fetched
Bin 546184 data fetched
Bin 426684 data fetched
Bin 436802 data fetched
Bin 521267 data fetched
Bin 483313 data fetched
Bin 415417 data fetched
Bin 518941 data fetched
Bin 512230 data fetched
Bin 426684 data fetched
Bin 443045 data fetched
Bin 446540 data fetched
Bin 512230 data fetched
Bin 420767 data fetched
Bin 400022 data fetched
Bin 434769 data fetched
Bin 436802 data fetched
Bin 414709 data fetched
Bin 435140 data fetched
Bin 410039 data fetched
Bin 517545 data fetched
Bin 414720 data fetched
Bin 517545 data fetched
Bin 400022 data fetched
Bin 414720 data fetched
Bin 440393 data fetched
Bin 372242 data fetched
Bin 414740 data fetched
Bin 601101 data fetched
Bin 515676 data fetched
Bin 438857 data fetched
Bin 419002 data fetched
Bin 521307 data fetched
Bin 528546 data fetched
Bin 414709 data fetched
Bin 403766 data fetched
Bin 553469 data fetched
Bin 552490 data fetched
Bin 531260 data fetched
Bin 478200 data fetched
Bin 401719 data fetched
Bin 601100 data fetched
Bin 379582 data fetched
Bin 419423 data fetched
Bin 443581 data fetched
Bin 448915 data fetched
Bin 440066 data fetched
Bin 440393 data fetched
Bin 448091 data fetched
Bin 425418 data fetched
Bin 443547 data fetched
Bin 601100 data fetched
Bin 498503 data fetched
Bin 376793 data fetched
Bin 546309 data fetched
Bin 446542 data fetched
Bin 415417 data fetched
Bin 601101 data fetched
Bin 559591 data fetched
Bin 440066 data fetched
Bin 379307 data fetched
Bin 373919 data fetched
Bin 463405 data fetched
Bin 414709 data fetched
Bin 414720 data fetched
Bin 443045 data fetched
Bin 443045 data fetched
Bin 527519 data fetched
Bin 377275 data fetched
Bin 414740 data fetched
Bin 440393 data fetched
Bin 425418 data fetched
Bin 411770 data fetched
Bin 425808 data fetched
Bin 414740 data fetched
Bin 419002 data fetched
Bin 414720 data fetched
Bin 440393 data fetched
Bin 429353 data fetched
Bin 552433 data fetched
Bin 449435 data fetched
Bin 402321 data fetched
Bin 400022 data fetched
Bin 525363 data fetched
Bin 601100 data fetched
Bin 483316 data fetched
Bin 400022 data fetched
Bin 559591 data fetched
Bin 410039 data fetched
Bin 415793 data fetched
Bin 438857 data fetched
Bin 511786 data fetched
Bin 414720 data fetched
Bin 425808 data fetched
Bin 544928 data fetched
Bin 545918 data fetched
Bin 438854 data fetched
Bin 438854 data fetched
Bin 414709 data fetched
Bin 423223 data fetched
Bin 426684 data fetched
Bin 514377 data fetched
Bin 517805 data fetched
Bin 414720 data fetched
Bin 400022 data fetched
Bin 425418 data fetched
Bin 546616 data fetched
Bin 414709 data fetched
Bin 374355 data fetched
Bin 448233 data fetched
Bin 414740 data fetched
Bin 432739 data fetched
Bin 403128 data fetched
Bin 486796 data fetched
Bin 475844 data fetched
Bin 426684 data fetched
Bin 534756 data fetched
Bin 414720 data fetched
Bin 542418 data fetched
Bin 420767 data fetched
Bin 440066 data fetched
Bin 403784 data fetched
Bin 483316 data fetched
Bin 527520 data fetched
Bin 400022 data fetched
Bin 438854 data fetched
Bin 379835 data fetched
Bin 403216 data fetched
Bin 414720 data fetched
Bin 515676 data fetched
Bin 407973 data fetched
Bin 527520 data fetched
Bin 538843 data fetched
Bin 601100 data fetched
Bin 514377 data fetched
Bin 410039 data fetched
Bin 414709 data fetched
Bin 440393 data fetched
Bin 515676 data fetched
Bin 426684 data fetched
Bin 413910 data fetched
Bin 481583 data fetched
Bin 425836 data fetched
Bin 434769 data fetched
Bin 474481 data fetched
Bin 411079 data fetched
Bin 601101 data fetched
Bin 601100 data fetched
Bin 427082 data fetched
Bin 510805 data fetched
Bin 533754 data fetched
Bin 601100 data fetched

In [32]:
bin_data_df = pd.DataFrame(bin_data)
bin_data_df.head()

,Type,Issuer,CardTier,CountryName
0,CREDIT,USAA SAVINGS BANK,PREMIER,United States
1,DEBIT,"U.S. BANK, N.A.",None,United States
2,CREDIT,"CAPITAL ONE BANK (USA), N.A.",SIGNATURE,United States
3,DEBIT,None,None,United States
4,DEBIT,"BANCO INTERAMERICANO DE FINANZAS, S.A.E.M.A.",CLASSIC,Peru

In [33]:
# conbine this into original df
df = pd.concat([df, bin_data_df], axis=1)

In [37]:
bin_data_df.tail()

     Type Issuer CardTier CountryName
895  None   None     None        None
896  None   None     None        None
897  None   None     None        None
898  None   None     None        None
899  None   None     None        None

In [49]:
df[['Bin', 'Price', 'Expiry', 'CountryName']].sort_values('Price', ascending=True).head(50)
# check Bin = 553469
# df[df['Bin'] == '530706']

        Bin          Price Expiry    CountryName
359  526924  10.50 $ 21.00  01/25           None
260  477874  10.50 $ 21.00  01/25           None
425  483313  10.50 $ 21.00  01/25           None
751  440393  10.50 $ 21.00  01/25           None
342  400022  10.50 $ 21.00  01/25           None
734  376793        15.75 $  06/28           None
554  376798        15.75 $  11/27           None
500  376783        18.90 $  07/28           None
361  410039        21.00 $  08/26           None
706  440393        21.00 $  10/28           None
358  601120        21.00 $  06/25           None
364  481583        21.00 $  11/28           None
357  510805        21.00 $  09/25           None
356  400022        21.00 $  11/27           None
704  400022        21.00 $  04/27           None
365  483313        21.00 $  06/28           None
366  537811        21.00 $  12/26           None
362  514968        21.00 $  06/28           None
449  400022        21.00 $  07/26           None
352  447098        21.00 $  02/25           None
700  410039        21.00 $  11/25           None
707  372242        21.00 $  01/28           None
350  419002        21.00 $  06/26           None
709  601101        21.00 $  08/27           None
348  443051        21.00 $  11/26           None
347  443045        21.00 $  07/25           None
710  515676        21.00 $  09/25           None
712  419002        21.00 $  01/28           None
713  521307        21.00 $  01/27           None
717  553469        21.00 $  02/27           None
718  552490        21.00 $  09/26           None
339  483313        21.00 $  07/25           None
338  423223        21.00 $  07/27           None
353  517546        21.00 $  10/28           None
368  466189        21.00 $  12/25           None
695  400022        21.00 $  11/26           None
696  434769        21.00 $  08/28           None
403  515676        21.00 $  10/27  United States
402  483313        21.00 $  10/28  United States
682  546184        21.00 $  05/28           None
400  440393        21.00 $  07/26  United States
397  483316        21.00 $  02/28  United States
396  402321        21.00 $  04/28         Russia
686  483313        21.00 $  12/27           None
688  518941        21.00 $  11/25           None
393  420767        21.00 $  05/28  United States
689  512230        21.00 $  09/26           None
391  526926        21.00 $  03/28  United States
390  545526        21.00 $  04/25  United States
389  545210        21.00 $  05/25  United States

In [35]:
df[['Bin', 'Price', 'Expiry', 'Issuer']].sort_values('Price', ascending=True).head(30)

        Bin          Price Expiry Issuer
359  526924  10.50 $ 21.00  01/25   None
260  477874  10.50 $ 21.00  01/25   None
425  483313  10.50 $ 21.00  01/25   None
751  440393  10.50 $ 21.00  01/25   None
342  400022  10.50 $ 21.00  01/25   None
734  376793        15.75 $  06/28   None
554  376798        15.75 $  11/27   None
500  376783        18.90 $  07/28   None
361  410039        21.00 $  08/26   None
706  440393        21.00 $  10/28   None
358  601120        21.00 $  06/25   None
364  481583        21.00 $  11/28   None
357  510805        21.00 $  09/25   None
356  400022        21.00 $  11/27   None
704  400022        21.00 $  04/27   None
365  483313        21.00 $  06/28   None
366  537811        21.00 $  12/26   None
362  514968        21.00 $  06/28   None
449  400022        21.00 $  07/26   None
352  447098        21.00 $  02/25   None
700  410039        21.00 $  11/25   None
707  372242        21.00 $  01/28   None
350  419002        21.00 $  06/26   None
709  601101        21.00 $  08/27   None
348  443051        21.00 $  11/26   None
347  443045        21.00 $  07/25   None
710  515676        21.00 $  09/25   None
712  419002        21.00 $  01/28   None
713  521307        21.00 $  01/27   None
717  553469        21.00 $  02/27   None